### ISSUE TITLE
python iot_lcd.py runnig for sometime

### ISSUE THREAD

**Issue by ktkirk** [ktkirk/HSSI#1]
root@edison:~/IoT# python iot_lcd.py 
Traceback (most recent call last):
  File "iot_lcd.py", line 70, in <module>
    p.log(device, temp, humid, lux_val, uv_val, moisture_val)
  File "/home/root/IoT/phant.py", line 47, in log
    response = self._session.post(self._get_url('input'), params=params)
  File "/home/root/IoT/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, *_kwargs)
  File "/home/root/IoT/requests/sessions.py", line 465, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/root/IoT/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/root/IoT/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Exiting
Exception KeyError: KeyError(-1217218816,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by ktkirk** [comment]
Add try block and made iot_once.py with systemd timer
